module.exports = [
  {
    trans_id: '1',
    trans_remarks: 'sample remarks',
    cheque_number: '112012',
    type: 'Dr',
    amount: '500',
    balance: '4500',
  },
  {
    trans_id: '2',
    trans_remarks: 'sample remarks',
    type: 'Dr',
    amount: '500',
    balance: '4000',
  },
  {
    trans_id: '3',
    trans_remarks: 'sample remarks',
    type: 'Cr',
    amount: '500',
    balance: '4500',
  },
  {
    trans_id: '4',
    trans_remarks: 'sample remarks',
    type: 'Cr',
    amount: '500',
    balance: '5000',
  },
  {
    trans_id: '5',
    trans_remarks: 'sample remarks 2',
    cheque_number: '112014',
    type: 'Dr',
    amount: '200',
    balance: '4500',
  },
  {
    trans_id: '6',
    trans_remarks: 'sample remarks 3',
    type: 'Cr',
    amount: '1000',
    balance: '4500',
  },
  {
    trans_id: '7',
    trans_remarks: 'sample remarks 4',
    cheque_number: '112015',
    type: 'Dr',
    amount: '100',
    balance: '4500',
  },
  {
    trans_id: '8',
    trans_remarks: 'sample remarks 5',
    type: 'Cr',
    amount: '5000',
    balance: '4500',
  },
  {
    trans_id: '9',
    trans_remarks: 'sample remarks 6 sample remarks 6 sample remarks',
    cheque_number: '112016',
    type: 'Dr',
    amount: '500',
    balance: '4500',
  },
  {
    trans_id: '10',
    trans_remarks: 'sample remarks 6 sample remarks 6 sample remarks',
    type: 'Dr',
    amount: '500',
    balance: '4500',
  },
  {
    trans_id: '11',
    trans_remarks: 'sample remarks 6 sample remarks 6 sample remarks',
    type: 'Dr',
    amount: '500',
    balance: '4500',
  },
  {
    trans_id: '12',
    trans_remarks: 'sample remarks 6 sample remarks 6 sample remarks',
    type: 'Dr',
    amount: '500',
    balance: '4500',
  },
  {
    trans_id: '13',
    trans_remarks: 'sample remarks 6 sample remarks 6 sample remarks',
    cheque_number: '112018',
    type: 'Dr',
    amount: '500',
    balance: '4500',
  },
  {
    trans_id: '14',
    trans_remarks: 'sample remarks 6 sample remarks 6 sample remarks',
    type: 'Dr',
    amount: '500',
    balance: '4500',
  },
  {
    trans_id: '15',
    trans_remarks: 'sample remarks 6 sample remarks 6 sample remarks',
    type: 'Dr',
    amount: '500',
    balance: '4500',
  },
  {
    trans_id: '16',
    trans_remarks: 'sample remarks 6 sample remarks 6 sample remarks',
    type: 'Dr',
    amount: '500',
    balance: '4500',
  },
];
